### ISSUE TITLE
Context menu for some extensions is missing

### ISSUE THREAD

**Issue by akuropka** [damienvanrobaeys/Run-in-Sandbox#18] opened 2021-11-16 15:18 UTC
Windows 22000.346

I downloaded the whole set as ZIP ([Run-in-Sandbox-master](https://codeload.github.com/damienvanrobaeys/Run-in-Sandbox/zip/refs/heads/master)) and extracted it. Afterwards I ran the .\Add_Structure.ps1 which completed without error (running it again without prior remove produces ResourceExists-errors).

The context menu for EXE is there and seems to work. But others are not available... how to track the issue down?

Thank you! (-:

![20211116_160939_explorer](https://user-images.githubusercontent.com/22570574/142012693-6e6fa0d9-2f10-43de-9151-591ad0f5f301.png)
![20211116_160735_explorer](https://user-images.githubusercontent.com/22570574/142012718-9f0bede0-076b-4d67-b157-beea69226c13.png)
![20211116_160641_explorer](https://user-images.githubusercontent.com/22570574/142012741-c02ffae7-0f8e-438f-bf87-10baf87e36c3.png)
![20211116_160825_explorer](https://user-images.githubusercontent.com/22570574/142012744-42281ec3-8531-47c9-9063-bbc02938e62c.png)
![20211116_160700_explorer](https://user-images.githubusercontent.com/22570574/142012746-1c7ad1c0-8165-4434-9284-66d5b69ed09c.png)

[RunInSandbox_Install.log](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7547675/RunInSandbox_Install.log)

**Comment by akuropka** [comment] 2021-11-16 15:28
Yes, it's Windows 11.
I added the install log (Restore point was not created due to one already created recently).

I tried EXE, ISO, ZIP and PS1 (just took any files for testing).

**Comment by damienvanrobaeys** [comment] 2021-11-16 15:49
ok because i don't see picture for iso i thought you tried on svg file.
Could you please check below locations:
HKCR\Windows.IsoFile\Shell
HKCU\.iso
HKCR\CompressedFolder\Shell
HKCR\WinRAR.ZIP\Shell
HKCR\.7z
HKCU\.ps1

**Comment by akuropka** [comment] 2021-11-16 16:05
HKCR\Windows.IsoFile\Shell
[1.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7548007/1.txt)

HKCR\.iso
[2.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7548009/2.txt)

HKCR\CompressedFolder\Shell
[3.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7548011/3.txt)

HKCR\WinRAR.ZIP\Shell
_does not exist_

HKCR\.7z
[4.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7548016/4.txt)

HKCR\.ps1
_does not exist_

**Comment by damienvanrobaeys** [comment] 2021-11-16 16:16
Actually it was hkcu for .iso and. Ps1

**Comment by akuropka** [comment] 2021-11-16 16:20
I was wondering about that but there's nothing like `HKCU\\.`.
Screenshot:
![20211116_171931_regedit](https://user-images.githubusercontent.com/22570574/142023859-48ce4e76-d8af-4446-9147-5ac386cb5a05.png)

**Comment by damienvanrobaeys** [comment] 2021-11-16 16:23
Hkcu > software > classes

**Comment by akuropka** [comment] 2021-11-16 18:55
Ah... `HKCU\Software\Classes\.iso` and `HKCU\Software\Classes\.ps1` do not exist.

**Comment by damienvanrobaeys** [comment] 2021-11-16 19:28
Regarding the iso part have you installed a tool for iso like CDBurnerXP ?

**Comment by akuropka** [comment] 2021-11-16 19:31
Yes, CDBurnerXP is installed.

**Comment by damienvanrobaeys** [comment] 2021-11-16 19:33
Ok I thik that's why when you install some soft it may change the way to integrate context menu.
I will proceed step by step, first with ISO.
I will update the add_structure and remove_structure in few minutes. I will inform you

**Comment by akuropka** [comment] 2021-11-16 19:35
top, thx!

**Comment by damienvanrobaeys** [comment] 2021-11-16 19:40
To be sure could you please check if there is something like as below ?
HKCR\iso-file
OR
HKCR\CDBurnerXP

**Comment by akuropka** [comment] 2021-11-16 19:45
Yes, `HKCR\iso-file` exists: [5.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7549363/5.txt)

**Comment by damienvanrobaeys** [comment] 2021-11-16 19:47
Could you please create a key like "hey hey" in HKCR\iso-file\shell ? not a string just a key
Then do a right-click on an iso, you should see hey hey

**Comment by akuropka** [comment] 2021-11-16 19:51
Yes, it works.
![20211116_205100_explorer](https://user-images.githubusercontent.com/22570574/142055748-f57cd0fd-b359-4592-a8e8-4277df3cba79.png)

**Comment by damienvanrobaeys** [comment] 2021-11-16 19:52
cool i will update files

**Comment by damienvanrobaeys** [comment] 2021-11-16 21:07
just updated sources.

You can test as below:
Do a remove-structure.ps1
Download new zip
Run add_structure.ps1

**Comment by akuropka** [comment] 2021-11-17 08:32
Thank you for your efforts.

Unfortunately it did not work.
The logfile did just contain eleven empty lines but there was a console output this time:

> [11.17.21 01:42:09] - INFO : Context menus for PS1 have been added
> [11.17.21 01:42:11] - INFO : Context menus for REG have been added
> [11.17.21 01:42:13] - INFO : Context menu for ISO has been added
> [11.17.21 01:42:13] - INFO : Checking content of HKCR\.ISO
> [11.17.21 01:42:13] - INFO : The key HKCR\.ISO exists
> [11.17.21 01:42:13] - INFO : Following subkeys found: (default) Content Type
> [11.17.21 01:42:13] - INFO : Following property found: iso-file
> [11.17.21 01:42:13] - INFO : Reg path to test: \iso-file
> [11.17.21 01:42:13] - INFO : The following reg path does not exist: \iso-file
> [11.17.21 01:42:13] - INFO : Following property found: CDBurnerXP/iso
> [11.17.21 01:42:13] - INFO : Reg path to test: \CDBurnerXP/iso
> [11.17.21 01:42:13] - INFO : The following reg path does not exist: \CDBurnerXP/iso
> [11.17.21 01:42:15] - INFO : Context menu for PPKG has been added
> [11.17.21 01:42:26] - INFO : Context menu for PS1 has been added
> [11.17.21 01:42:26] - INFO : Context menus for VBS have been added
> [11.17.21 01:42:26] - INFO : Context menus for EXE have been added
> [11.17.21 01:42:26] - INFO : Context menu for MSI has been added
> [11.17.21 01:42:26] - INFO : Context menu for ZIP has been added
> [11.17.21 01:42:30] - INFO : Context menu for 7Z has been added
> [11.17.21 01:42:33] - INFO : Context menu for MSIX has been added
> [11.17.21 01:42:33] - INFO : Context menu for ISO has been added
> [11.17.21 01:42:33] - INFO : Context menus for folder have been added

**Comment by damienvanrobaeys** [comment] 2021-11-17 08:40
oops seems a bad copy paste in my scripts will change this

**Comment by damienvanrobaeys** [comment] 2021-11-17 09:11
I just updated the add_structure.ps1 could you please try again ?

**Comment by damienvanrobaeys** [comment] 2021-11-17 09:23
yeah, now it's not working for PS1, ZIP ? Have you tried msi too ?

**Comment by akuropka** [comment] 2021-11-17 13:51
I was just going through the known extensions:
- Run EXE ✅
- Run PS1 ❌ (my default app: MS Powershell ISE)
- Run ZIP ❌ (my default app: 7-zip)
- Share folder ✅
- Run PPKG ✅
- Run Intunewin ✅
- Run MSIX ✅
- Run MSI ✅
- Run VBS ✅ (incl. run with parameters)
- Extract ISO ✅
- Test REG ✅
- Open HTML ❌ (my default app: Firefox)
- Install multiple apps ✅ (SDBAPP extension)

**Comment by damienvanrobaeys** [comment] 2021-11-17 14:50
Could you please check below locations ?
HKCU\software\classes\.ps1
HKCU\software\classes\AppXxf01pj590w7z9mxmyv3nx0a9ewj3e51g
HKCR\FirefoxHTML

**Comment by akuropka** [comment] 2021-11-17 15:23
`HKCU\software\classes\.ps1` ❌
`HKCU\software\classes\AppXxf01pj590w7z9mxmyv3nx0a9ewj3e51g` ❌, while some other AppX are there
`HKCR\FirefoxHTML` ❌, but: `HKCR\FirefoxHTML-BA1BED273568656F`
`HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\UserChoice` ✅
`HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.html\UserChoice` ✅
`HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.zip`  ✅

**Comment by damienvanrobaeys** [comment] 2021-11-17 15:28
For those one below could you please send me a txt file as before ?
HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\UserChoice 
HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.html\UserChoice 
HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.zip
HKCR\.ps1

**Comment by akuropka** [comment] 2021-11-17 15:50
Sorry... of course: [FileExts.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7556005/FileExts.txt)

`HKCR\.ps1`
_does not exist_

**Comment by damienvanrobaeys** [comment] 2021-11-17 20:57
Thanks
Could you please check below location:
HKCU\software\classes\Applications\\powershell_ise.exe

**Comment by damienvanrobaeys** [comment] 2021-11-17 21:06
Ok, I think I found why for PS1 and HTML.
I will update files soon

**Comment by akuropka** [comment] 2021-11-18 01:04
`HKCU\software\classes\Applications\powershell_ise.exe`: [powershell_ise.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7559015/powershell_ise.txt)

**Comment by damienvanrobaeys** [comment] 2021-11-18 07:45
Just updated files.
Could you please test again for PS1 and HTML ?

**Comment by akuropka** [comment] 2021-11-18 11:28
Looks both great! 👍😀

**Comment by damienvanrobaeys** [comment] 2021-11-18 15:21
cool :-)
Now regarding ZIP, do you have below locations ?
HKCU\software\classes\7-Zip.zip
HKCR\7-Zip.zip

**Comment by akuropka** [comment] 2021-11-18 15:31
Yes... [7-Zip.zip.txt](https://github.com/damienvanrobaeys/Run-in-Sandbox/files/7563943/7-Zip.zip.txt)

**Comment by damienvanrobaeys** [comment] 2021-11-18 15:39
ok will work on it.
thanks

**Comment by akuropka** [comment] 2021-11-18 15:48
Great, thank you again.

**Comment by damienvanrobaeys** [comment] 2021-11-22 10:33
and if you create a new key like toto in HKCR\7-Zip.zip\shell do you see it when you do a right-click on a zip file ?

**Comment by akuropka** [comment] 2021-11-22 16:15
Yes!
![20211122_170936](https://user-images.githubusercontent.com/22570574/142895760-39c86d7a-2acf-4c72-a602-56136a014de7.png)

Btw your script is installing 7-Zip (for own purposes) as well. Maybe it makes sense to check if 7z is already installed and skip copying and using the own one in this case.

**Comment by damienvanrobaeys** [comment] 2021-11-22 17:53
Actually it doesn't install 7zip just copy required file for extracting iso but nothing is installed on the device

**Comment by akuropka** [comment] 2021-11-23 05:29
Yeah, "installing" by copying to ProgramData and using ist. Just noticed...

**Comment by damienvanrobaeys** [comment] 2021-11-23 11:43
Just updated sources files.
Could you please try again for zip ?

**Comment by akuropka** [comment] 2021-11-23 14:00
It works... great! 😀👍

Btw I noticed if you extract an iso in the sandbox there's no progress bar. Depending on the size of the iso or the infrastructure used it may take a while until everything is ready.

Another idea coming into my mind was not to extract an iso but to mount it. This should be sufficient since there's no persistent storage anyway.

**Comment by damienvanrobaeys** [comment] 2021-11-23 14:11
You're right i will add a msgbox when iso is flully extracted.
Yep, actually the second case is in my plan, thanks for the suggestion.
Thanks for your feedback :-)

**Comment by akuropka** [comment] 2021-11-23 14:14
Btw do you have any ☕/🍺 box?

**Comment by damienvanrobaeys** [comment] 2021-11-23 21:03
You mean something like pay me a coffee on my blog ?

**Comment by akuropka** [comment] 2021-11-24 10:12
Exactly, but didn’t find anything.

**Comment by akuropka** [comment] 2021-11-25 17:32
Maybe something like [Custom Context Menu](https://github.com/ikas-mc/ContextMenuForWindows11) would make things easier... (however, it's for Windows 11 only)

**Comment by Joly0** [comment] 2022-09-07 08:22
.cmd context menu option is missing aswell, .svg works

**Comment by orestisthebeast** [comment] 2023-04-19 13:17
Hi there and thank you for your work. I am also on Windows 10 and can confirm that all context menus apart from .PS1 are working. Any pointers?

**Comment by Joly0** [comment] 2023-04-19 19:29
> Hi there and thank you for your work. I am also on Windows 10 and can confirm that all context menus apart from .PS1 are working. Any pointers?

Hey, i have a fork https://github.com/Joly0/Run-in-Sandbox which i have a pr open aswell (hasnt been merged yet). 
I have fixed alot of issues i had with this version, maybe it helps you too. Could you maybe try that and see, if it works? If not, please open an issue over there and i will look into it asap

**Comment by orestisthebeast** [comment] 2023-04-20 11:43
Joly0's fork works on Win10, confirmed.

Thank you so much!

**Comment by Joly0** [comment] 2023-04-20 12:01
> Joly0's fork works on Win10, confirmed.
> 
> Thank you so much!

You’re welcome

**Comment by ak47uk** [comment] 2023-05-17 14:09
In case it helps anyone, I could not get this to work with PS1, all other extensions I tested were ok. Notepad++ was set as my default for PS1, I ran Remove_Structure.ps1, reset all default apps in Windows 11, ran Add_Structure.ps1 and then it worked. I got this error on every run, including the successful one and using Joly0 fork:
`[05/17/23 15:04:48] - INFO : Checking programs from: Registry::HKEY_USERS\S-1-12-1-...\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\UserChoice                                       Test-Path : Cannot bind argument to parameter 'Path' because it is null.                                                At C:\Users\USER\Run-in-Sandbox-master\Add_Structure.ps1:296 char:18               +             If (Test-Path $HKCR_UserChoice_Shell) {                                                                   +                           ~~~~~~~~~~~~~~~~~~~~~~                                                                          + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException                             + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand `

**Comment by Joly0** [comment] 2023-05-17 22:35
> In case it helps anyone, I could not get this to work with PS1, all other extensions I tested were ok. Notepad++ was set as my default for PS1, I ran Remove_Structure.ps1, reset all default apps in Windows 11, ran Add_Structure.ps1 and then it worked. I got this error on every run, including the successful one and using Joly0 fork: `[05/17/23 15:04:48] - INFO : Checking programs from: Registry::HKEY_USERS\S-1-12-1-...\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\UserChoice Test-Path : Cannot bind argument to parameter 'Path' because it is null. At C:\Users\USER\Run-in-Sandbox-master\Add_Structure.ps1:296 char:18 + If (Test-Path $HKCR_UserChoice_Shell) { + ~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidData: (:) [Test-Path], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand `

I think i have fixed this, opened a pr for it

**Comment by ak47uk** [comment] 2023-05-18 07:12
> > I think i have fixed this, opened a pr for it

That works now, many thanks!

**Comment by damienvanrobaeys** [comment] 2023-06-06 13:38
Could ou please try with the new version ?

**Comment by damienvanrobaeys** [comment] 2023-06-07 10:22
thanks :-)

**Closed by damienvanrobaeys** 2023-06-07 10:22 UTC
